### ISSUE TITLE
[Security] Unsafe Check

### ISSUE THREAD

**Issue by mustakimur** [veorq/sgx-reencrypt#1]
The `reencrypt()` has an unsafe check of certification validation. The method accepts an untrusted data `*clid` or client id based on which the enclave extract policy. The certificate expiration is one of the sensitive data in the policy and it is validated against an untrusted timestamp collected by an OCALL. As both sides of the data of the validation are untrusted, an attacker could bypass it and forced to reuse an expired certificate. The parts of the code have shown here:
```cpp
int 
reencrypt(client_id *clid, uint8_t *request,
           size_t requestlen, uint8_t *response,
                          size_t *responselen) {
  ...
  if((ret = check_policy(&keyin, &keyout, *clid,
                         keyIDin, keyIDout)) 
                              != REENCRYPT_OK) {
    ...
  }
  if(ret = unsafe_timestamp(&timestamp) 
                             != REENCRYPT_OK){
    ...
  }
  if (timestamp > keyin->expiration_date ||
    timestamp > keyout->expiration_date) {
    ret = REENCRYPT_KEY_EXPIRED;
    goto err;
  }
  if ((ret = decrypt(&m, &mlen,c,clen,
                    keyin)) != REENCRYPT_OK) {
    ...   
  }
}
```

**Comment by luismerino** [comment]
Thanks for reporting this. As we stated in the Security Notes (see https://github.com/kudelskisecurity/sgx-reencrypt#security-notes): 

> At the moment, there's no trusted absolute time source inside the enclave, and the timestamp is requested through an untrusted call to the system, rendering the expiration date policy forgeable by a malicious enclave host.

Although there are schemes we could have used to provision a trusted source for time, they are out of the scope of this project.

I'll leave this open for some time, just in case @veorq has something to say.

**Comment by mustakimur** [comment]
Thanks for the clarification.
